function rosterStudioHtml() {
  return `<!doctype html><html><head><meta charset="utf-8"><title>CH2K8 Roster Studio</title><style>
body{margin:0;background:#0d1117;color:#e6edf3;font-family:Segoe UI,Arial,sans-serif}header{padding:18px 22px;border-bottom:1px solid #30363d;background:#111827}h1{margin:0;font-size:24px}.muted{color:#8b949e}.bar{display:grid;grid-template-columns:1fr 1fr auto;gap:10px;padding:14px 18px;border-bottom:1px solid #30363d;background:#0d1117}.row{display:flex;gap:8px}input,select,textarea{width:100%;box-sizing:border-box;background:#0d1117;color:#e6edf3;border:1px solid #30363d;border-radius:10px;padding:9px}textarea{min-height:150px;font-family:Consolas,monospace;font-size:12px}button{border:0;border-radius:10px;padding:9px 12px;color:white;background:#238636;font-weight:700;cursor:pointer}.browse,.tab{background:#30363d}.content{padding:18px}.panel{background:#161b22;border:1px solid #30363d;border-radius:14px;padding:14px;margin-bottom:14px}.tabs{display:flex;flex-wrap:wrap;gap:8px;padding:12px 18px;border-bottom:1px solid #30363d}.tab.active{background:#8957e5}.kv{display:grid;grid-template-columns:150px 1fr;gap:6px;font-size:13px}.chip{display:inline-block;padding:3px 7px;border-radius:999px;background:#30363d;margin:2px}.swatch{display:inline-block;width:28px;height:18px;border:1px solid #8b949e;vertical-align:middle;margin-right:6px}table{border-collapse:collapse;width:100%;font-size:12px}th,td{border-bottom:1px solid #30363d;padding:6px;text-align:left}pre{white-space:pre-wrap;font-size:12px}@media(max-width:900px){.bar{grid-template-columns:1fr}.kv{grid-template-columns:1fr}}
</style></head><body><header><h1>CH2K8 Roster Studio</h1><div class="muted">Built-in Edit School schema, roster research, save-copy exporter, and field confidence labels.</div></header><section class="bar"><div class="row"><input id="rosterPath" placeholder="Roster source: roster_english.iff, USERDATA, save ZIP, or raw ROST"><button class="browse" data-target="rosterPath" data-kind="file">Browse</button></div><div class="row"><input id="assetRoot" placeholder="Optional extracted/ripped asset folder"><button class="browse" data-target="assetRoot" data-kind="folder">Browse</button></div><button id="openBtn">Open Roster</button></section><nav class="tabs" id="tabs"></nav><main class="content" id="content"><section class="panel"><h2>Open a roster source</h2><p class="muted">This page uses the built-in CH2K8 schema. Export saves a new copy and never overwrites the input.</p></section></main><script>
let state=null,tab='Dashboard',teamIndex=268;
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function post(u,d){let r=await fetch(u,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});if(!r.ok)throw new Error(await r.text());let j=await r.json();if(j.error)throw new Error(j.error);return j;}
function smallTable(rows,cols,max=80){rows=(rows||[]).slice(0,max);return '<table><thead><tr>'+cols.map(c=>'<th>'+esc(c[1]||c[0])+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cols.map(c=>'<td>'+esc(typeof c[0]==='function'?c[0](r):r[c[0]])+'</td>').join('')+'</tr>').join('')+'</tbody></table>';}
function tabs(){let ts=state?.schema?.tabs||['Dashboard'];if(state&&!ts.includes('Export Edits'))ts=['Export Edits',...ts];document.getElementById('tabs').innerHTML=ts.map(t=>'<button class="tab '+(t===tab?'active':'')+'" data-tab="'+esc(t)+'">'+esc(t)+'</button>').join('');}
function team(){return state?.teams?.find(t=>Number(t.team_index)===Number(teamIndex))||state?.teams?.[0];}
function teamPicker(){return '<label class="muted">Selected team</label><select id="teamPick">'+(state?.teams||[]).map(t=>'<option value="'+t.team_index+'" '+(Number(t.team_index)===Number(teamIndex)?'selected':'')+'>'+esc(t.team_index+' - '+(t.school_name||t.short_name||t.abbreviation))+'</option>').join('')+'</select>';}
function dashboard(){return '<section class="panel"><h2>Dashboard</h2><pre>'+esc(JSON.stringify({source:state.source,counts:state.counts},null,2))+'</pre></section><section class="panel"><h2>Write safety</h2>'+Object.entries(state.schema.writeSafety||{}).map(([k,v])=>'<h3>'+esc(k)+'</h3>'+v.map(x=>'<span class="chip">'+esc(x)+'</span>').join('')).join('')+'</section>';}
function exportPanel(){let sample=[{type:'palette',teamIndex:teamIndex,slot:1,value:'00FF00FF'}];return '<section class="panel"><h2>Export edited copy</h2><p class="muted">Paste edit operations as JSON. Supported types: palette, string, rival, rosterSlot, rotationSlot. Output mode: userdata for PS3 USERDATA-style file, raw for raw ROST payload. This never overwrites the source path.</p><label>Output path</label><input id="outputPath" placeholder="C:/mods/UGA_test_USERDATA"><label>Output mode</label><select id="outputMode"><option value="userdata">userdata</option><option value="raw">raw</option></select><label>Edit operations JSON</label><textarea id="editJson">'+esc(JSON.stringify(sample,null,2))+'</textarea><button id="exportBtn">Export Copy</button><pre id="exportResult"></pre></section><section class="panel"><h2>Operation examples</h2><pre>'+esc(JSON.stringify([{type:'palette',teamIndex:teamIndex,slot:1,value:'00FF00FF'},{type:'string',teamIndex:teamIndex,field:'nickname',value:'Bulldogs'},{type:'rival',teamIndex:teamIndex,rivalNumber:4,targetTeamIndex:12},{type:'rosterSlot',teamIndex:teamIndex,slot:0,playerIndex:3328},{type:'rotationSlot',teamIndex:teamIndex,slot:0,playerIndex:3328}],null,2))+'</pre></section>';}
function school(){let t=team();return '<section class="panel">'+teamPicker()+'<h2>School</h2><div class="kv"><b>School Name</b><span>'+esc(t.school_name||t.short_name)+'</span><b>Nickname</b><span>'+esc(t.mascot_plural)+'</span><b>Abbreviation</b><span>'+esc(t.abbreviation)+'</span><b>City</b><span class="muted">visible UI field; storage not confirmed</span><b>State</b><span class="muted">visible UI field; storage not confirmed</span><b>Logo Design</b><span>N/A locked for default real teams</span></div></section><section class="panel"><h2>Primary / Secondary candidates</h2>'+palette([0,1,14,15,16,17])+'</section>';}
function spirit(){let t=team();let r=t.research||{};return '<section class="panel">'+teamPicker()+'<h2>Spirit</h2><div class="kv"><b>Mascot text</b><span>'+esc(t.mascot_name)+'</span><b>Fight Song</b><span class="muted">visible UI field; storage not confirmed</span><b>Mid. Madness</b><span>'+esc(t.event_name||'')+'</span><b>Student Section</b><span>'+esc(t.student_section||'')+'</span><b>Mascot model candidate</b><span>'+esc((r.assetWords||[]).find(x=>x.offset==='+0x190')?.value||'')+'</span></div></section><section class="panel"><h2>Rivals #1-#5</h2>'+smallTable(r.rivals||[],[['slot','Slot'],['offset','Offset'],['teamIndex','Team index']])+'</section>';}
function palette(slots){let t=team();let rows=(t.palette||[]).filter(p=>!slots||slots.includes(p.slot));return smallTable(rows,[[r=>'<span class="swatch" style="background:'+r.css+'"></span>'+r.slot,'Slot'],['offset','Offset'],['hex','RGB/control'],['uiHint','Likely UI use'],['status','Confidence']],slots?50:200).replace(/&lt;span/g,'<span').replace(/&quot;/g,'"').replace(/&gt;/g,'>');}
function floor(){return '<section class="panel">'+teamPicker()+'<h2>Floor color research</h2><p class="muted">Basketball Logo and Volleyball Lines are N/A locked for default real teams. Editable floor colors use the shared 31-word RGB/control material block.</p>'+palette()+'</section>';}
function basket(){return '<section class="panel">'+teamPicker()+'<h2>Basket</h2><p class="muted">Basket variation is visible but not mapped. Basket Front/Rear/Metal are expected to be material slots.</p>'+palette()+'</section>';}
function cheer(){return '<section class="panel">'+teamPicker()+'<h2>Cheerleader</h2><p class="muted">Display Model is deprioritized. Primary/Secondary/Tertiary are expected material slots.</p>'+palette()+'</section>';}
function rosterSlots(kind){let t=team();let key=kind==='rotation'?'rotationSlots':'rosterSlots';let title=kind==='rotation'?'Depth Chart / Rotation':'Roster Slots';return '<section class="panel">'+teamPicker()+'<h2>'+title+'</h2>'+smallTable(t.research?.[key]||[],[['slot','Slot'],['offset','Offset'],['playerIndex','Player index']])+'</section>';}
function assets(){let t=team();let a=t.assets||{};let rows=Object.keys(a).filter(k=>typeof a[k]==='object').map(k=>({key:k,...a[k]}));return '<section class="panel">'+teamPicker()+'<h2>Uniforms & Assets</h2><p>Asset ID: '+esc(t.asset_id)+'</p>'+smallTable(rows,[['key','Key'],['label','Label'],['fileName','File'],[r=>r.found?'yes':'no','Found'],['path','Path']],50)+'</section>';}
function conferences(){return '<section class="panel"><h2>Conference table</h2><p class="muted">Conference table is mapped. Team-to-conference/legacy swap storage is not proven yet.</p>'+smallTable(state.conferences||[],[['conference_index','#'],['name','Name'],['abbreviation','Abbr'],['rank','Rank'],['tournament_slots','Tourney slots'],['row_offset','Row']],80)+'</section>';}
function unknown(){let t=team();return '<section class="panel">'+teamPicker()+'<h2>Unknown / Research</h2><pre>'+esc(JSON.stringify({teamResearch:t.research,schema:state.schema.builtIn.TEAM_FIELDS},null,2))+'</pre></section>';}
function render(){tabs();if(!state)return;let html='';if(tab==='Export Edits')html=exportPanel();else if(tab==='Dashboard')html=dashboard();else if(tab==='School')html=school();else if(tab==='Spirit')html=spirit();else if(tab==='Floor')html=floor();else if(tab==='Basket')html=basket();else if(tab==='Coach')html='<section class="panel">'+teamPicker()+'<h2>Coach</h2><p class="muted">Team coach pointers are mapped; coach row fields are visible in decoded coach records/research.</p>'+smallTable(state.coaches||[],[['coach_index','#'],['first_name','First'],['last_name','Last']],80)+'</section>';else if(tab==='Cheerleader')html=cheer();else if(tab==='Roster Slots')html=rosterSlots('roster');else if(tab==='Depth Chart / Rotation')html=rosterSlots('rotation');else if(tab==='Uniforms & Assets')html=assets();else if(tab==='Conferences / Legacy Swaps')html=conferences();else html=unknown();document.getElementById('content').innerHTML=html;let p=document.getElementById('teamPick');if(p)p.onchange=()=>{teamIndex=Number(p.value);render();};let b=document.getElementById('exportBtn');if(b)b.onclick=exportCopy;}
async function exportCopy(){try{let edits=JSON.parse(document.getElementById('editJson').value||'[]');let result=await post('/api/roster/export',{rosterPath:document.getElementById('rosterPath').value,outputPath:document.getElementById('outputPath').value,outputMode:document.getElementById('outputMode').value,edits});document.getElementById('exportResult').textContent=JSON.stringify(result,null,2);}catch(err){document.getElementById('exportResult').textContent=err.message||String(err);}}
document.addEventListener('click',async e=>{if(e.target.classList.contains('tab')){tab=e.target.dataset.tab;render();return;}if(!e.target.classList.contains('browse'))return;try{let r=await post('/api/browse',{kind:e.target.dataset.kind});if(r.path)document.getElementById(e.target.dataset.target).value=r.path;}catch(err){alert(err.message||err);}});
document.getElementById('openBtn').onclick=async()=>{try{state=await post('/api/roster/open',{rosterPath:document.getElementById('rosterPath').value,assetRoot:document.getElementById('assetRoot').value});tab='Export Edits';teamIndex=state.teams?.find(t=>t.abbreviation==='UGA')?.team_index ?? state.teams?.[0]?.team_index ?? 0;render();}catch(err){alert(err.message||err);}};
tabs();
</script></body></html>`;
}

module.exports = { rosterStudioHtml };
